name: Build MapNavigator2D

on:
  push:
    branches:
      - main
      - dev
      - feat/*
      - fix/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: "latest"

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install GLEW, GLFW and FreeType
        run: |
          .\vcpkg\vcpkg.exe install glew:x64-windows glfw3:x64-windows freetype:x64-windows
          .\vcpkg\vcpkg.exe integrate install

      - name: Restore NuGet packages
        run: nuget restore MapNavigator2D.sln

      - name: Build solution
        run: msbuild MapNavigator2D.sln /p:Configuration=Release /p:Platform=x64 /p:VcpkgTriplet=x64-windows
